"""POST-HOC, EXPLORATORY (session 26, 2026-10-07): the X1 combined gate (CUSUM) with the split-conformal threshold
(N6, alpha 0.05) instead of the default (1 - fpr) quantile, on the same TEST items and attacks as X1, with the DSG
comparator runs. Decided after the X1 TEST verdict was seen; NOT a claim-rule input (claims.evaluate drops every run
whose config purpose is "posthoc-exploratory"); DEVIATIONS row 2026-10-07.

    python cluster/x1_posthoc.py build   # branch exp/PH-X1-conformal (= X1's pinned 93625f5 + one config file)
    python cluster/x1_posthoc.py stage   # snapshot, 0 lab-queue writes: specs + ORDER/SNAPSHOT go to gpuws only

Experiment PH-X1-conformal = X1.yaml filtered to the 60 dsg-faithful runs and the 60 gated/cusum runs, with
calib.rule = conformal (fpr 0.05 read as alpha; dsgx.methods.gates.calibrate at 93625f5 supports it; the conformal
rule has its own calibration cache key) and labels combined -> combined-conformal. base.purpose = posthoc-exploratory.
No base runs and no attack-success task (not needed for the CUSUM-vs-DSG comparison). Runs on gpuws with
cluster/lab_jobs.py --group x1-posthoc (runs/PH-X1-conformal/HARDWARE.json = gpuws); never on the lab queue.
"""
import copy
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
X1_COMMIT = "93625f5daf04740f62a1f9dcd842f90838f586f3"  # LABJOBS_PIN of the gpuws X1 replica
BRANCH = "exp/PH-X1-conformal"
EXP = "PH-X1-conformal"
CFG = f"configs/experiments/{EXP}.yaml"
GROUP = "x1-posthoc"
PURPOSE = "posthoc-exploratory"
SERVER = "/home/suraj/dsg_cluster"


def git(*a, cwd=REPO, **kw):
    return subprocess.run(["git", *a], cwd=cwd, check=True, text=True, capture_output=True, **kw).stdout.strip()


def config() -> dict:
    y = yaml.safe_load(git("show", f"{X1_COMMIT}:configs/experiments/X1.yaml"))
    runs = []
    for r in y["runs"]:
        m = r["method"]
        if m["name"] == "dsg-faithful":
            runs.append(copy.deepcopy(r))
        elif m["name"] == "gated" and (m.get("gate") or {}).get("type") == "cusum":
            r = copy.deepcopy(r)
            r["method"]["calib"]["rule"] = "conformal"
            r["dataset_label"] = r["dataset_label"].replace("combined", "combined-conformal", 1)
            r["combine"]["cond"] = "combined-conformal"
            runs.append(r)
    assert sum(r["method"]["name"] == "gated" for r in runs) == 60 and len(runs) == 120, len(runs)
    return {"exp_id": EXP, "priority": "stretch", "wave": 7,
            "base": dict(y["base"], purpose=PURPOSE), "runs": runs, "jobs": y["jobs"]}


HEADER = ("# POST-HOC, EXPLORATORY (decided 2026-10-07 after the X1 TEST verdict; not a claim-rule input; DEVIATIONS).\n"
          "# X1 combined gate (CUSUM) with the split-conformal threshold (N6, alpha 0.05) + DSG comparators, same TEST\n"
          "# items and attacks as X1. Generated by prep cluster/x1_posthoc.py from X1.yaml at 93625f5; do not edit.\n")


def build() -> int:
    if git("branch", "--list", BRANCH):
        print(f"{BRANCH} exists at {git('rev-parse', BRANCH)}")
        return 0
    with tempfile.TemporaryDirectory(dir=REPO.parent / "dsg_results_cluster") as td:
        wt = Path(td) / "wt"
        git("worktree", "add", "--detach", str(wt), X1_COMMIT)
        try:
            (wt / CFG).write_text(HEADER + yaml.safe_dump(config(), sort_keys=False))
            git("add", CFG, cwd=wt)
            git("commit", "-q", "-m", f"{EXP}: POST-HOC, EXPLORATORY config (X1 CUSUM gate with the conformal threshold, "
                "alpha 0.05, + DSG comparators, same TEST items and attacks); not a claim-rule input", cwd=wt)
            sha = git("rev-parse", "HEAD", cwd=wt)
            git("branch", BRANCH, sha)
        finally:
            git("worktree", "remove", "--force", str(wt))
    print(f"{BRANCH} = {sha}")
    return 0


def stage() -> int:
    commit = git("rev-parse", BRANCH)
    snap = f"PHX1-{commit[:7]}"
    with tempfile.TemporaryDirectory(dir=REPO.parent / "dsg_results_cluster") as td:
        td = Path(td)
        code = td / "code"
        code.mkdir()
        subprocess.run(f"git -C {REPO} archive {commit} | tar -x -C {code} --exclude figures", shell=True, check=True)
        (code / "CODE_COMMIT.json").write_text(json.dumps(
            {"commit": commit, "branch": BRANCH, "dirty": False, "snapshot": f"code-{snap}", "posthoc": True}) + "\n")
        # plan with the pinned code itself (same chunking as the lab enqueue)
        out = subprocess.run([sys.executable, "-c", (
            "import json,sys; from dsgx.queue.enqueue import jobs_from_experiment as j; "
            f"print(json.dumps(j('{CFG}', worktree='.')))")], cwd=code, env={**os.environ, "PYTHONPATH": str(code), "CUDA_VISIBLE_DEVICES": ""}, check=True, text=True, capture_output=True).stdout
        jobs = json.loads(out.strip().splitlines()[-1])
        (td / "specs").mkdir()
        order = []
        for s in jobs:
            s = dict(s, worktree=f"{SERVER}/code-{snap}", commit=None, pinned_commit=commit, config_path=CFG,
                     deps=[d for d in s.get("deps", []) if d.startswith(EXP)], branch=BRANCH, priority="stretch",
                     posthoc={"exploratory": True, "claim_input": False, "decided": "2026-10-07 after X1 TEST verdict"},
                     moved_to_server={"group": GROUP, "lab_worktree": None, "lab_commit": None, "replica": False})
            (td / "specs" / f"{s['id']}.json").write_text(json.dumps(s, indent=1))
            order.append(s["id"])
        (td / "ORDER").write_text("\n".join(order) + "\n")
        (td / "SNAPSHOT").write_text(snap + "\n")
        print(f"{len(order)} jobs ({sum(len(s['run_indices']) for s in jobs)} runs), commit {commit[:10]}, snapshot code-{snap}")
        sh = lambda c: subprocess.run(c, shell=True, check=True)  # noqa: E731
        sh(f"""ssh -n -o BatchMode=yes gpuws "printf -- '- %s | %s | %s\\n' \\"\\$(date '+%F %T')\\" 'rsync code-{snap}/ + {len(order)} job specs + labjobs/{GROUP}/' 'x1_posthoc.py stage (POST-HOC exploratory, session 26)' >> ~/dsg_cluster/COMMAND_LOG.md" """)
        sh(f"ssh -n gpuws 'mkdir -p ~/dsg_cluster/results/queue/jobs ~/dsg_cluster/labjobs/{GROUP}'")
        sh(f"rsync --bwlimit=50000 --partial -a --delete {code}/ gpuws:dsg_cluster/code-{snap}/ </dev/null")
        sh(f"rsync --bwlimit=50000 --partial -a {td}/specs/ gpuws:dsg_cluster/results/queue/jobs/ </dev/null")
        sh(f"rsync --bwlimit=50000 --partial -a {td}/ORDER {td}/SNAPSHOT gpuws:dsg_cluster/labjobs/{GROUP}/ </dev/null")
    return 0


if __name__ == "__main__":
    sys.exit({"build": build, "stage": stage}[sys.argv[1]]())
